# docker exec -it sql_db bash
# docker exec -it sql_db psql -U admin -d sql_db

# docker compose -f docker-compose-db.yml up -d

version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: pg_sql_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5431:5432
    volumes:
      - ./sql_db_volume/:/var/lib/postgresql/data
      - ./sql/00_init.sql:/docker-entrypoint-initdb.d/init.sql
